package org.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class TemperatureUnitDAO {
    private static final List<TemperatureUnit> DEFAULT_UNITS = List.of(
            new TemperatureUnit(1, "Celsius", "°C"),
            new TemperatureUnit(2, "Fahrenheit", "°F"),
            new TemperatureUnit(3, "Kelvin", "K")
    );

    public List<TemperatureUnit> getAllUnits() {
        try (Connection connection = DBConnection.getConnection()) {
            createTable(connection);
            seedDefaults(connection);
            return readUnits(connection);
        } catch (SQLException exception) {
            throw new IllegalStateException(
                    "Unable to load temperature units. Configure TEMPERATURE_DB_URL, "
                            + "TEMPERATURE_DB_USER, and TEMPERATURE_DB_PASSWORD.",
                    exception);
        }
    }

    private void createTable(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS temperature_units (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(30) NOT NULL UNIQUE,
                        symbol VARCHAR(10) NOT NULL
                    )
                    """);
        }
    }

    private void seedDefaults(Connection connection) throws SQLException {
        String sql = "INSERT INTO temperature_units (name, symbol) VALUES (?, ?) "
                + "ON CONFLICT (name) DO NOTHING";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            for (TemperatureUnit unit : DEFAULT_UNITS) {
                statement.setString(1, unit.getName());
                statement.setString(2, unit.getSymbol());
                statement.addBatch();
            }
            statement.executeBatch();
        }
    }

    private List<TemperatureUnit> readUnits(Connection connection) throws SQLException {
        List<TemperatureUnit> units = new ArrayList<>();
        try (Statement statement = connection.createStatement();
             ResultSet results = statement.executeQuery(
                     "SELECT id, name, symbol FROM temperature_units ORDER BY id")) {
            while (results.next()) {
                units.add(new TemperatureUnit(
                        results.getInt("id"),
                        results.getString("name"),
                        results.getString("symbol")));
            }
        }
        return units;
    }

    static List<TemperatureUnit> defaultUnitsForTests() {
        return DEFAULT_UNITS;
    }
}
